//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcommEntities2 : DbContext
    {
        public EcommEntities2()
            : base("name=EcommEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminDetails_Table> AdminDetails_Table { get; set; }
        public virtual DbSet<Cart_item> Cart_item { get; set; }
        public virtual DbSet<Product_table> Product_table { get; set; }
        public virtual DbSet<UserReg_Table> UserReg_Table { get; set; }
        public virtual DbSet<order_Details> order_Details { get; set; }
    }
}
