//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product_table()
        {
            this.Cart_item = new HashSet<Cart_item>();
        }
    
        public int P_ID { get; set; }
        public string P_Name { get; set; }
        public string P_Image { get; set; }
        public Nullable<int> P_Price { get; set; }
        public string P_Description { get; set; }
        public Nullable<int> P_Fk_ID { get; set; }
    
        public virtual AdminDetails_Table AdminDetails_Table { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart_item> Cart_item { get; set; }
    }
}
